### ISSUE TITLE
Ktor in About section

### ISSUE THREAD

**Issue by tanujnotes** [AhmedOmara14/NewsApp#1]
Why have you mentioned Ktor in your project's About section when you're using Retrofit?

**Comment by AhmedOmara14** [comment]
yes, I used ktor instead of retrofit. you can find retrofit in master branch and ktor in ktor client branch, please switch to it. [Ktor-Client](https://github.com/AhmedOmara14/NewsApp/tree/Ktor-client)

**Comment by tanujnotes** [comment]
Got it. Thanks.
